### ISSUE TITLE
We should update Docker-PowerShell module name to match.

### ISSUE THREAD

**Issue by jterry75** [Microsoft/Docker-PowerShell#112]
Currently the `Docker-PowerShell` module is named `Docker`. It seems more reasonable to call it `Docker-PowerShell` right? 

The only changes would be:
```PS
> Install-Module Docker-PowerShell
> Import-Module Docker-PowerShell
```

**Comment by jstarks** [comment]
What other PowerShell modules have PowerShell in the name?

**Comment by swernli** [comment]
I'm in favor of leaving this as is... the module name is descriptive enough, because the fact that is a powershell module is implied by the fact you are importing it into powershell using Install-Module.  But the repository is named Docker-PowerShell to differentiate from the actual docker product fork.  I don't feel like the names should have to match, because it is named reasonable for identifying it.

**Comment by jterry75** [comment]
Yea my fear is that `Install-Package Docker` will conflict someday. But I guess then you would just have to add `-Source DockerPS-Dev` or whatever feed you meant for Docker PS.
