### ISSUE TITLE
get-container should take "-name" as a parameter

### ISSUE THREAD

**Issue by BenjaminArmstrong** [Microsoft/Docker-PowerShell#75]
Pretty hard to get a single container right now

**Comment by swernli** [comment]
This one is a tricky issue... Docker's engine api doesn't give us a graceful way to request one ContainerListResponse object or multiple ContainerResponse objects due to the way their rest endpoints are designed.  We'll need to dig further, but it's likely that whatever we do now will be a work-around until the engine api is improved.

**Comment by jterry75** [comment]
I know its 100% less than ideal but we could theoretically just do client side processing for now. IE: get the full list but only write out the one that matches the -Id or -Name requested. We should open a tracking item in Docker to add the /containers/json to support /containers/json?id=<> in the filters list.

**Comment by jterry75** [comment]
Also, I haven't had a chance to try but what if we used since=<id>&limit=1? Is it inclusive?

**Comment by swernli** [comment]
Oh man... I didn't realize that since and before took ID/name.  I thought those were timestamps.  I'll give that a try and it could solve our issue (if since/before are inclusive).
